name: CI

on: [push, pull_request]

env:
  GITHUB_EVENT_NAME: ${{ github.event_name }}

jobs:

  ### BUILD windows

  windows-build:
    runs-on: ubuntu-22.04
    env:
      TARGET_ARCH: amd64-windows

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          chmod u+x ./build.sh
          ./build.sh build ./out_win.txt

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: "out-windows" #destination
          path: ./out_win.txt #source

  ### BUILD linux

  linux-build:
    runs-on: ubuntu-22.04
    env:
      TARGET_ARCH: amd64-linux

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          chmod u+x ./build.sh
          ./build.sh build ./out_lin.txt

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: "out-linux" #destination
          path: ./out_lin.txt #source

  ### TEST windows

  windows-test:
    needs: [windows-build]
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: out-windows #source
          path: ./out_win.txt #destination

      - name: Test
        shell: cmd
        run: |
          build.bat test ./out_win.test.txt

  ### TEST linux

  linux-test:
    needs: [linux-build]
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: out-linux #source
          path: ./out_lin.txt #destination

      - name: Test
        run: |
          chmod u+x ./build.sh
          ./build.sh test ./out_win.test.txt

  ### Release

  release:
    needs: [windows-test, linux-test]
    runs-on: ubuntu-22.04

    steps:

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: out-windows #source
          path: ./out_win.txt #destination

      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: out-linux #source
          path: ./out_lin.txt #destination

      # TODO : make github release

