name: CI

on: [push, pull_request]

jobs:

  ### windows

  windows-build:
    runs-on: ubuntu-22.04
    env:
      BUILD_MODE: build
      TARGET_ARCH: amd64-windows

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: chmod u+x ./build.sh ; ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: "out-windows" #destination
          path: build/release/* #source

  windows-test:
    needs:
      - windows-build
    runs-on: windows-2019
    env:
      BUILD_MODE: test
      TARGET_ARCH: amd64-windows

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: out-windows #source
          path: build/release #destination
      - shell: cmd
        run: build.bat

  ### linux

  linux-build:
    runs-on: ubuntu-22.04
    env:
      BUILD_MODE: build
      TARGET_ARCH: amd64-linux

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: chmod u+x ./build.sh; ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: "out-linux" #destination
          path: build/release/* #source

  linux-test:
    needs:
      - linux-build
    runs-on: ubuntu-22.04
    env:
      BUILD_MODE: test
      TARGET_ARCH: amd64-linux

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: out-linux #source
          path: build/release #destination
      - run: chmod u+x ./build.sh; ./build.sh

  ### raspberry

  raspberry-build:
    runs-on: ubuntu-22.04
    env:
      BUILD_MODE: build
      TARGET_ARCH: armhf-linux

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - run: chmod u+x ./build.sh; ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: "out-raspberry" #destination
          path: build/release/* #source

  raspberry-test:
    needs:
      - raspberry-build
    runs-on: ubuntu-22.04
    env:
      BUILD_MODE: test
      TARGET_ARCH: armhf-linux

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: out-raspberry #source
          path: build/release #destination
      - uses: pguyot/arm-runner-action@v2
        with:
          commands: chmod u+x ./build.sh; ./build.sh

  ### Release

  release:
    if: github.event_name == 'push'
    needs:
      - windows-test
      - linux-test
      - raspberry-test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: out-windows #source
          path: release #destination
      - uses: actions/download-artifact@v3
        with:
          name: out-linux #source
          path: release #destination

      - name: Download Raspberry artifact
        uses: actions/download-artifact@v3
        with:
          name: out-raspberry #source
          path: release #destination

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: Automatic Release (${{ github.event.head_commit.timestamp }})
          tag_name: release.${{ github.sha }}
          files: release/*

